title: Leap Day theme
description: This repository serves as a central hub for my most impactful, well-documented projects, combining analytical rigour with clean, reproducible code.
show_downloads: true
google_analytics:
theme: jekyll-theme-leap-day
